### ISSUE TITLE
Feature-Request: sync main course data

### ISSUE THREAD

**Issue by stdoma** [juacas/moodle-format_redirected#1]
The easy linking of courses for teachers is an important point for us.
Currently this is still a little complicated. With the plugin, our teachers become a little more independent. But they still want a few improvements.

It would be good if the forwarded course could automatically sync information from the main course: visibility, start and end date, description, picture and name.
The name should be considered separately from the information. This can and should differ in different course areas.
The background is the direct presentation of the information in the course area of the forwarded course. Now you would have to maintain this several times.

You could possibly install this in such a way that there are checkboxes if you change the course format to forwarding.
The update process would have to be triggered in the background if the settings in the main course were changed. Alternatively, you could do this with a cron job.
(Unfortunately, I don't know enough about Moodle programming to be able to assess this correctly.)

**Comment by juacas** [comment]
Hi @stdoma ,
thanks for using this plugin and suggesting new features. However, your suggestions need further analysis due to the following argument: More than a course can be the "target" of a "forwarded" course. Hence, in general, the suggested synchronization of several "target" course's data can't be properly defined.
By now, this plugin acts only as a gentle redirection.
